
services:
  db:
    image: postgres:14.18-bookworm
    container_name: bookmarkuser-nestjs-db
    restart: always
    environment:
      POSTGRES_DB: bookmarkuser-nestjs-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432" # localhost - docker
    volumes:
      - bookmarkuser-nestjs_data:/var/lib/postgresql/data

volumes:
  bookmarkuser-nestjs_data:
